version: '3.3'

services:
   db:
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
       MYSQL_DATABASE: ${DB_DATABASE}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}

   wordpress:
     volumes:
      - ${ROOT_VOLUME_DIR}/wp-content:/var/www/html/wp-content
      - ${ROOT_VOLUME_DIR}/wp_data/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./wp/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     ports:
       - "8000:80"
     environment:
       WORDPRESS_DB_HOST: ${DB_HOST}:${DB_PORT}
       WORDPRESS_DB_USER: ${DB_USER}
       WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
       WORDPRESS_DB_NAME: ${DB_DATABASE}
volumes:
    db_data: {}
    wp_data:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: ${ROOT_VOLUME_DIR}